[package]
authors = [
    "Romain Liautaud <romain.liautaud@snips.ai>",
    "Mathieu Poumeyrol <kali@zoy.org>",
]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
]
license = "MIT/Apache-2.0"
name = "tract"
repository = "https://github.com/snipsco/tract"
version = "0.4.2-pre"

[badges.travis-ci]
repository = "snipsco/tract"

[dependencies]
ansi_term = "0.12.0"
atty = "0.2"
box_drawing = "0.1"
clap = "2.31"
env_logger = "0.6"
error-chain = "0.12"
itertools = "0.8"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
ndarray = "0.12"
pbr = "1.0"
py_literal = "0.2"
rand = "0.7"

[dependencies.ndarray-npy]
features = ["compressed_npz"]
version = "0.4.2-pre"

[dependencies.tract-core]
path = "../core"

[dependencies.tract-kaldi]
optional = true
version = "0.4.2-pre"

[dependencies.tract-onnx]
optional = true
version = "0.4.2-pre"

[dependencies.tract-tensorflow]
optional = true
version = "0.4.2-pre"

[features]
conform = ["tract-tensorflow/conform"]
default = [
    "kaldi",
    "onnx",
    "tf",
]
kaldi = ["tract-kaldi"]
onnx = ["tract-onnx"]
tf = ["tract-tensorflow"]
