[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
]
license = "MIT/Apache-2.0"
name = "tract-core"
repository = "https://github.com/snipsco/tract"
version = "0.4.2-pre"

[[bench]]
harness = false
name = "conv_direct_vs_im2col"

[[bench]]
harness = false
name = "im2col_inception"
[badges.travis-ci]
repository = "snipsco/tract"

[dependencies]
bit-set = "0.5"
derive-new = "0.5"
downcast-rs = "1.0"
env_logger = "0.6"
error-chain = "0.12"
half = "1.3"
itertools = "0.8"
log = "0.4"
maplit = "1.0"
no-panic = "0.1"
num-integer = "0.1"
num-traits = "0.2"
objekt = "0.1.1"
smallvec = "0.6"
unsafe_unwrap = "0.1.0"

[dependencies.ndarray]
version = "0.4.2-pre"

[dependencies.serde]
optional = true
version = "0.4.2-pre"

[dependencies.serde_derive]
optional = true
version = "0.4.2-pre"

[dependencies.tract-linalg]
path = "../linalg"

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[features]
default = []
serialize = [
    "serde",
    "serde_derive",
    "smallvec/serde",
    "half/serde",
]
