[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
    "ONNX",
]
license = "MIT/Apache-2.0"
name = "tract-tensorflow"
repository = "https://github.com/snipsco/tract"
version = "0.4.2-pre"

[badges.travis-ci]
repository = "snipsco/tract"

[dependencies]
derive-new = "0.5"
error-chain = "0.12"
itertools = "0.8"
log = "0.4"
num-traits = "0.2"
protobuf = "2.0"

[dependencies.ndarray]
version = "0.4.2-pre"

[dependencies.tensorflow]
optional = true
version = "0.4.2-pre"

[dependencies.tract-core]
path = "../core"

[dependencies.tract-linalg]
path = "../linalg"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.6"
proptest = "0.9"
rand = "0.7"

[features]
conform = ["tensorflow"]
