[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
    "ONNX",
]
license = "MIT/Apache-2.0"
name = "tract-onnx"
repository = "https://github.com/snipsco/tract"
version = "0.4.2-pre"

[badges.travis-ci]
repository = "snipsco/tract"

[dependencies]
derive-new = "0.5"
error-chain = "0.12"
itertools = "0.8"
log = "0.4"
num-integer = "0.1"
num-traits = "0.2"
protobuf = "2.0"
smallvec = "0.6"

[dependencies.ndarray]
version = "0.4.2-pre"

[dependencies.tract-core]
path = "../core"

[dependencies.tract-linalg]
path = "../linalg"
