name: Embedded targets

on:
  push:

jobs:
  linux:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Cross script
      run: .travis/cross.sh

